# Generated by Django 5.1.2 on 2024-11-03 03:32

import detection.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=32, unique=True)),
                ('image', models.ImageField(unique=True, upload_to=detection.models.upload_path)),
                ('processed_image', models.ImageField(unique=True, upload_to='processed/')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField()),
                ('label', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.detection')),
            ],
        ),
    ]
