name: computerparts

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        IMAGE_PROCESSOR_URL: ${IMAGE_PROCESSOR_URL}
    expose:
      - 3000
    volumes:
      - staticfiles:/app/dist/static:ro
    links:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - 8000
    volumes:
      - staticfiles:/app/static

volumes:
  staticfiles:
