name: computerparts

services:
  web:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    volumes:
      - db_data:/usr/src/app/db
      - static_files:/usr/src/app/static
      - uploads:/usr/src/app/uploads
  proxy:
    image: nginx:latest
    # ports:
    #   - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_files:/etc/nginx/static
      - uploads:/etc/nginx/uploads

volumes:
  static_files:
  db_data:
  uploads:
